version: '3.8'
services:
  php-apache: 
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "8005:80"
    volumes:
      - ../laravel:/var/www
  mysql-db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
  npm:
    build:
      context: ./npm
      dockerfile: Dockerfile
    volumes:
      - ../laravel:/var/www
    entrypoint: ['npm']
volumes:
  mysql: